INSERT INTO TB_JOGADOR
VALUES('RONALDO','9','ATACANTE',2);

INSERT INTO TB_JOGADOR
VALUES('RIVALDO','10','MEIA-ATACANTE',2);

INSERT INTO TB_JOGADOR
VALUES('ROBERTO CARLOS','6','LATERAL ESQUERDO',2);

INSERT INTO TB_JOGADOR
VALUES('CAFU','2','LATERAL DIREITO',2);

INSERT INTO TB_JOGADOR
VALUES('MARCOS','12','GOLEIRO',2);