SELECT * FROM TB_JOGADOR;

SELECT NM_JOGADOR, NR_JOGADOR
FROM TB_JOGADOR;


SELECT NM_JOGADOR
FROM TB_JOGADOR
WHERE NR_JOGADOR = '2';


SELECT DS_POSICAO
FROM TB_JOGADOR
WHERE ID_JOGADOR >=7 AND ID_JOGADOR <=9;


SELECT ID_JOGADOR, NM_JOGADOR, NR_JOGADOR,DS_POSICAO,DT_PARTIDA
FROM TB_JOGADOR
INNER JOIN TB_PARTIDA
ON (TB_JOGADOR.TB_PARTIDAID_PARTIDA = TB_PARTIDA.ID_PARTIDA)
ORDER BY TB_PARTIDA.DT_PARTIDA DESC;