UPDATE TB_JOGADOR
SET TB_PARTIDAID_PARTIDA = 2
WHERE ID_JOGADOR = 1;

UPDATE TB_JOGADOR
SET TB_PARTIDAID_PARTIDA =4
WHERE ID_JOGADOR = 3;

UPDATE TB_JOGADOR
SET TB_PARTIDAID_PARTIDA = 1
WHERE ID_JOGADOR = 2;